/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ActionButtonProps {
  text: string;
  href: string;
}

const ActionButton: React.FC<ActionButtonProps> = ({ text, href }) => {
  return (
    <button className="gap-2.5 self-stretch px-4 py-9 mt-8 text-4xl leading-none text-white bg-slate-900 min-h-[92px] rounded-[50px]">
      <a href={href}>{text}</a>
    </button>
  );
};

export default ActionButton;
