/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HeaderProps {}

const Header: React.FC<HeaderProps> = () => {
  return (
    <header className="mr-16 text-8xl max-md:mr-2.5 max-md:max-w-full max-md:text-4xl">
      SPEECH2TXT
    </header>
  );
};

export default Header;
